import test from 'node:test';
import assert from 'node:assert/strict';

const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:4181';
async function request(path, { cookie, ...options } = {}) { const response = await fetch(`${base}${path}`, { ...options, headers: { 'content-type': 'application/json', ...(cookie ? { cookie } : {}) } }); const body = response.status === 204 ? {} : await response.json(); return { response, body, cookie: response.headers.get('set-cookie')?.split(';')[0] }; }
async function login(username, password, role) { const captcha = await request('/api/auth/captcha'); const answer = [...captcha.body.svg.matchAll(/<text[^>]*>([^<]+)<\/text>/g)].map(match => match[1]).join(''); return request('/api/auth/login', { method: 'POST', body: JSON.stringify({ username, password, role, captchaId: captcha.body.id, captcha: answer }) }); }

test('assessment first-phase resource, paper, assignment and auto grading flow', async () => {
  const parentLogin = await login('admin', 'admin@2026', 'parent'); assert.equal(parentLogin.response.status, 200); const parent = parentLogin.cookie;
  const suffix = Date.now(); const created = await request('/api/parent/students', { cookie: parent, method: 'POST', body: JSON.stringify({ displayName: '评测测试学生', username: `assessment_student_${suffix}`, password: 'Student2026A', grade: '三年级' }) }); assert.equal(created.response.status, 201); const studentId = created.body.student.id;
  const library = await request('/api/parent/assessment-resource-libraries', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `语文三上词语-${suffix}`, subject: '语文', resourceType: '词语', grade: '三年级' }) }); assert.equal(library.response.status, 201);
  const imported = await request(`/api/parent/assessment-resource-libraries/${library.body.library.id}/import`, { cookie: parent, method: 'POST', body: JSON.stringify({ items: [{ content: '翩翩起舞', note: '形容轻快地跳舞' }, { content: '津津有味', note: '形容有滋味、有兴趣' }] }) }); assert.equal(imported.response.status, 201); assert.equal(imported.body.inserted, 2);
  const libraryItems = await request(`/api/parent/assessment-resource-libraries/${library.body.library.id}/items`, { cookie: parent }); assert.equal(libraryItems.response.status, 200); assert.equal(libraryItems.body.items.length, 2); assert.equal(libraryItems.body.items[0].content, '翩翩起舞');
  const updatedLibrary = await request(`/api/parent/assessment-resource-libraries/${library.body.library.id}`, { cookie: parent, method: 'PATCH', body: JSON.stringify({ name: `语文三上词语修订-${suffix}`, subject: '语文', resourceType: '四字词语', grade: '三年级' }) }); assert.equal(updatedLibrary.response.status, 200); assert.equal(updatedLibrary.body.library.resourceType, '四字词语');
  const deletedItems = await request(`/api/parent/assessment-resource-libraries/${library.body.library.id}/items`, { cookie: parent, method: 'DELETE', body: JSON.stringify({ ids: [libraryItems.body.items[0].id] }) }); assert.equal(deletedItems.response.status, 200); assert.equal(deletedItems.body.deleted, 1);
  const filteredItems = await request(`/api/parent/assessment-resource-libraries/${library.body.library.id}/items?q=津津`, { cookie: parent }); assert.equal(filteredItems.response.status, 200); assert.equal(filteredItems.body.items.length, 1);
  const question = await request('/api/parent/assessment-questions', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `自动判分题-${Date.now()}`, subject: '英语', questionType: 'single_choice', promptText: 'Choose A', options: ['A', 'B'], correctAnswer: 'A', score: 5, status: 'published' }) }); assert.equal(question.response.status, 201); const questionId = question.body.question.id;
  const lifecycleQuestion = await request('/api/parent/assessment-questions', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `可编辑简答题-${suffix}`, subject: '语文', questionType: 'short_text', promptText: '写下你的阅读感受', correctAnswer: '围绕文章内容作答', allowAttachment: true, score: 8, status: 'published', gradingMode: 'manual', source: { attachments: [{ name: '阅读提示.txt', mime: 'text/plain', kind: 'file', data: 'data:text/plain;base64,6ZiF6K+75o+Q56S6' }] } }) }); assert.equal(lifecycleQuestion.response.status, 201);
  const lifecycleId = lifecycleQuestion.body.question.id;
  const disabledQuestion = await request(`/api/parent/assessment-questions/${lifecycleId}`, { cookie: parent, method: 'PATCH', body: JSON.stringify({ status: 'archived' }) }); assert.equal(disabledQuestion.response.status, 200); assert.equal(disabledQuestion.body.question.status, 'archived'); assert.equal(disabledQuestion.body.question.prompt.allowAttachment, true);
  const enabledQuestion = await request(`/api/parent/assessment-questions/${lifecycleId}`, { cookie: parent, method: 'PATCH', body: JSON.stringify({ status: 'published' }) }); assert.equal(enabledQuestion.response.status, 200); assert.equal(enabledQuestion.body.question.status, 'published');
  const lifecycleDetail = await request(`/api/parent/assessment-questions/${lifecycleId}`, { cookie: parent }); assert.equal(lifecycleDetail.response.status, 200); assert.equal(lifecycleDetail.body.question.source.attachments[0].name, '阅读提示.txt');
  const deletedQuestion = await request(`/api/parent/assessment-questions/${lifecycleId}`, { cookie: parent, method: 'DELETE' }); assert.equal(deletedQuestion.response.status, 200); assert.equal(deletedQuestion.body.deleted, true);
  const paper = await request('/api/parent/assessment-papers', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `测试题单-${Date.now()}`, subject: '英语', questionIds: [questionId] }) }); assert.equal(paper.response.status, 201); assert.equal(paper.body.paper.questionCount, 1); assert.equal(paper.body.paper.totalScore, 5); assert.equal(paper.body.paper.questions, undefined);
  const paperDetail = await request(`/api/parent/assessment-papers/${paper.body.paper.id}`, { cookie: parent }); assert.equal(paperDetail.response.status, 200); assert.equal(paperDetail.body.paper.questions.length, 1);
  const assignment = await request('/api/parent/assessment-assignments', { cookie: parent, method: 'POST', body: JSON.stringify({ paperId: paper.body.paper.id, studentId, dueDate: new Date().toISOString().slice(0, 10) }) }); assert.equal(assignment.response.status, 201);
  const studentLogin = await login(`assessment_student_${suffix}`, 'Student2026A', 'student'); assert.equal(studentLogin.response.status, 200); const student = studentLogin.cookie; const list = await request('/api/student/assessments', { cookie: student }); const item = list.body.assessments.find(assessment => assessment.id === assignment.body.assignmentIds[0] || assessment.taskId); assert.ok(item);
  const started = await request(`/api/student/assessments/${item.taskId}/start`, { cookie: student, method: 'POST' }); assert.equal(started.response.status, 200); const questionRow = started.body.assessment.questions[0];
  assert.equal((await request(`/api/student/assessments/${item.taskId}/answers/${questionRow.id}`, { cookie: student, method: 'PUT', body: JSON.stringify({ answer: 'A' }) })).response.status, 200);
  const submitted = await request(`/api/student/assessments/${item.taskId}/submit`, { cookie: student, method: 'POST', body: JSON.stringify({ requestId: `assessment-test-${Date.now()}` }) }); assert.equal(submitted.response.status, 200); assert.equal(submitted.body.assessment.taskStatus, 'completed'); assert.equal(submitted.body.assessment.attempt.finalScore, 5);
  assert.equal(submitted.body.assessment.questions[0].correctAnswer.correct, 'A');
  const retryPaper = await request('/api/parent/assessment-papers', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `可重试题单-${suffix}`, subject: '英语', passScore: 5, allowRetry: true, questionIds: [questionId] }) }); assert.equal(retryPaper.response.status, 201);
  const retryAssignment = await request('/api/parent/assessment-assignments', { cookie: parent, method: 'POST', body: JSON.stringify({ paperId: retryPaper.body.paper.id, studentId, dueDate: new Date().toISOString().slice(0, 10) }) }); assert.equal(retryAssignment.response.status, 201);
  const retryItem = (await request('/api/student/assessments', { cookie: student })).body.assessments.find(assessment => assessment.id === retryAssignment.body.assignmentIds[0]); assert.ok(retryItem);
  const retryStarted = await request(`/api/student/assessments/${retryItem.taskId}/start`, { cookie: student, method: 'POST' }); const retryQuestion = retryStarted.body.assessment.questions[0];
  assert.equal((await request(`/api/student/assessments/${retryItem.taskId}/answers/${retryQuestion.id}`, { cookie: student, method: 'PUT', body: JSON.stringify({ answer: 'B' }) })).response.status, 200);
  const retryFailed = await request(`/api/student/assessments/${retryItem.taskId}/submit`, { cookie: student, method: 'POST', body: JSON.stringify({ requestId: `assessment-retry-fail-${Date.now()}` }) }); assert.equal(retryFailed.body.assessment.attempt.finalScore, 0); assert.equal(retryFailed.body.assessment.canRetry, true); assert.equal(retryFailed.body.assessment.questions[0].correctAnswer.correct, 'A');
  const retryStartedAgain = await request(`/api/student/assessments/${retryItem.taskId}/retry`, { cookie: student, method: 'POST' }); assert.equal(retryStartedAgain.response.status, 200); assert.equal(retryStartedAgain.body.assessment.attempt.version, 2);
  assert.equal((await request(`/api/student/assessments/${retryItem.taskId}/answers/${retryQuestion.id}`, { cookie: student, method: 'PUT', body: JSON.stringify({ answer: 'A' }) })).response.status, 200);
  const retryPassed = await request(`/api/student/assessments/${retryItem.taskId}/submit`, { cookie: student, method: 'POST', body: JSON.stringify({ requestId: `assessment-retry-pass-${Date.now()}` }) }); assert.equal(retryPassed.body.assessment.attempt.finalScore, 5); assert.equal(retryPassed.body.assessment.canRetry, false);
  assert.equal((await request(`/api/student/assessments/${retryItem.taskId}/retry`, { cookie: student, method: 'POST' })).response.status, 409);
  const manualQuestion = await request('/api/parent/assessment-questions', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `审核题-${suffix}`, subject: '英语', questionType: 'short_text', promptText: '写一句英文问候', correctAnswer: 'Hello', score: 5, status: 'published', gradingMode: 'manual' }) }); assert.equal(manualQuestion.response.status, 201);
  const manualPaper = await request('/api/parent/assessment-papers', { cookie: parent, method: 'POST', body: JSON.stringify({ name: `审核题单-${suffix}`, subject: '英语', questionIds: [manualQuestion.body.question.id] }) }); assert.equal(manualPaper.response.status, 201);
  const manualAssignment = await request('/api/parent/assessment-assignments', { cookie: parent, method: 'POST', body: JSON.stringify({ paperId: manualPaper.body.paper.id, studentId, dueDate: new Date().toISOString().slice(0, 10), stars: 2, petExpWeight: 1, needsReview: true }) }); assert.equal(manualAssignment.response.status, 201);
  const pendingItem = (await request('/api/student/assessments', { cookie: student })).body.assessments.find(assessment => assessment.id === manualAssignment.body.assignmentIds[0]); assert.ok(pendingItem);
  const pendingStarted = await request(`/api/student/assessments/${pendingItem.taskId}/start`, { cookie: student, method: 'POST' }); const pendingQuestion = pendingStarted.body.assessment.questions[0];
  assert.equal((await request(`/api/student/assessments/${pendingItem.taskId}/answers/${pendingQuestion.id}`, { cookie: student, method: 'PUT', body: JSON.stringify({ answer: 'Hello teacher' }) })).response.status, 200);
  const pendingSubmitted = await request(`/api/student/assessments/${pendingItem.taskId}/submit`, { cookie: student, method: 'POST', body: JSON.stringify({ requestId: `assessment-review-${Date.now()}` }) }); assert.equal(pendingSubmitted.body.assessment.taskStatus, 'pending_review');
  const pendingResults = await request('/api/parent/assessment-results?status=pending_review', { cookie: parent }); const pendingResult = pendingResults.body.results.find(assessment => assessment.id === manualAssignment.body.assignmentIds[0]); assert.ok(pendingResult);
  const reviewDetail = await request(`/api/parent/assessment-results/${pendingResult.id}`, { cookie: parent }); assert.equal(reviewDetail.response.status, 200); assert.equal(reviewDetail.body.assessment.questions[0].correctAnswer.correct, 'Hello');
  const genericReviews = await request('/api/parent/reviews?studentId=all&period=all', { cookie: parent }); assert.equal(genericReviews.body.reviews.some(task => task.taskType === 'assessment'), false);
  const reviewed = await request(`/api/parent/assessment-results/${pendingResult.id}/review`, { cookie: parent, method: 'POST', body: JSON.stringify({ action: 'approve', answers: [{ questionId: pendingQuestion.id, score: 3 }], finalScore: 3, stars: 4, petExpWeight: 2, message: '回答很认真' }) }); assert.equal(reviewed.response.status, 200); assert.equal(reviewed.body.finalScore, 3);
  const finalizedDetail = await request(`/api/parent/assessment-results/${pendingResult.id}`, { cookie: parent }); assert.equal(finalizedDetail.body.assessment.attempt.finalScore, 3); assert.equal(finalizedDetail.body.assessment.stars, 4); assert.equal(finalizedDetail.body.assessment.petExpWeight, 2); assert.equal(finalizedDetail.body.assessment.reviewMessage, '回答很认真');
  const removedLibrary = await request(`/api/parent/assessment-resource-libraries/${library.body.library.id}`, { cookie: parent, method: 'DELETE' }); assert.equal(removedLibrary.response.status, 200); const papersAfterLibraryDeletion = await request('/api/parent/assessment-papers', { cookie: parent }); assert.ok(papersAfterLibraryDeletion.body.papers.some(item => item.id === paper.body.paper.id));
});
